-- Slot 4 of the 30-day social calendar: a new recurring content type,
-- mixed alongside the existing 3 daily posts rather than replacing any
-- of them (see 20260823110000 for the schema change this depends on).
--
-- Two kinds of post, alternating through the month:
--   theme 'Trivia'    A real fact about a real glo-temp.com city, sourced
--                     from city-trivia-data.js -- verbatim facts already
--                     vetted for that file (see its own header comment:
--                     "safely-true, widely-documented facts").
--   theme 'Lost city' A real, excavated, dated ancient site from
--                     lost-cities-data.js's `ANCIENT` list -- verified
--                     history, no legend framing needed because none of
--                     it is legend.
--   theme 'Legend'    A myth from lost-cities-data.js's `LEGEND` list.
--                     Every caption states plainly, in its own words,
--                     that the place was never found / isn't real --
--                     the same non-negotiable that file's header comment
--                     enforces for /gem: "A visitor must never be able
--                     to come away thinking Atlantis is a confirmed
--                     location." image_search_term for these points at
--                     a real, documented artwork (Atlantis, El Dorado)
--                     or a real place the legend is set near/named after
--                     (Shangri-La's real Yunnan county, the real Bay of
--                     Douarnenez, the real Land's End coast, the real
--                     Hawikuh pueblo site, the real Lake Svetloyar) --
--                     never fantasy art of the mythical place itself,
--                     which could read as a depiction of somewhere real.
--                     Hyperborea has no such real anchor, so it carries
--                     no image_search_term at all -- social-next-post
--                     already handles that case, serving a plain brand
--                     card rather than nothing (see its own comment).
insert into social_content_queue
  (day_number, slot_number, scheduled_time, platform, format, theme, caption, image_search_term)
values
  (1, 4, '16:30', 'instagram', 'Single image', 'Trivia', 'Cairo sits close enough to the Great Pyramid of Giza that it''s basically a neighbour to the last standing wonder of the ancient world. 🏙️🐫 And Al-Azhar University, founded in 970, is STILL teaching classes today -- older than most countries currently on a map. Some cities have history. Cairo never stopped making it. #glotemp #Cairo', 'Cairo skyline with Great Pyramid of Giza'),
  (2, 4, '16:30', 'instagram', 'Single image', 'Lost city', 'They call it the Treasury, but nobody ever found gold in it. 🏛️ Legend said a pharaoh hid his fortune in the stone urn above Al-Khazneh''s door -- so for centuries, people literally shot at it hoping gold would spill out. It''s a tomb. It was always a tomb. Petra, Jordan: carved by the Nabataeans over 2,000 years ago, unknown to Europe until 1812. Real place, real history, occasionally real bullet holes. #glotemp #LostCities', 'Petra Jordan Treasury Al-Khazneh facade'),
  (3, 4, '16:30', 'instagram', 'Single image', 'Trivia', 'Istanbul is the only city on Earth that sits on two continents -- Europe on one side of the Bosphorus, Asia on the other, one bridge apart. The Grand Bazaar has been trading under one roof since 1461, and it''s still going. Some cities pick a side. Istanbul just built a bridge. 🌉 #glotemp #Istanbul', 'Istanbul Bosphorus bridge skyline'),
  (4, 4, '16:30', 'instagram', 'Carousel (2 slides)', 'Legend', 'According to Plato, Atlantis was a naval power beyond the Pillars of Heracles that grew greedy, attacked Athens, and was swallowed by the sea in a single day and night. 🌊 Here''s the twist: his own student Aristotle seems to have thought he made it up. No coordinates. No ruins. No trace, anywhere, ever. Atlantis isn''t a lost city -- it''s a 2,400-year-old cautionary tale with an unreasonably good marketing team. Swipe for the only map anyone ever seriously drew of it. →', 'Mundus Subterraneus Athanasius Kircher Atlantis map'),
  (5, 4, '16:30', 'instagram', 'Single image', 'Trivia', 'Some cities have a metro. Moscow has underground palaces. 🚇✨ Several stations come with chandeliers, mosaics and marble like they''re expecting royalty on the 6:15. And Red Square isn''t named for communism -- ''red'' in old Russian also just meant ''beautiful.'' Moscow was doing branding before branding was a word. #glotemp #Moscow', 'Moscow Metro station chandelier mosaic'),
  (6, 4, '16:30', 'instagram', 'Single image', 'Lost city', 'The Spanish conquistadors never found Machu Picchu. Not because it was hidden -- because the Inca simply never told them it was there. 🏔️ Built around 1450 at 2,430 metres, its finest walls are cut so precisely they hold with zero mortar and flex rather than collapse in earthquakes. When it was ''discovered'' in 1911, local farming families were already living on the site. They just hadn''t mentioned it to anyone with an army. #glotemp #LostCities', 'Machu Picchu Peru wide shot'),
  (7, 4, '16:30', 'instagram', 'Single image', 'Trivia', 'There''s a whole country inside Rome. Vatican City -- its own nation, complete with its own postal service -- sits entirely within Rome''s city limits. Meanwhile the Trevi Fountain quietly collects around €1 million a year in tossed coins, all donated to charity. Rome: technically two capitals, one very expensive wishing well. 🪙 #glotemp #Rome', 'Trevi Fountain Rome'),
  (8, 4, '16:30', 'instagram', 'Carousel (2 slides)', 'Legend', 'El Dorado wasn''t a golden city. It was never even a place. It was a MAN -- ''el hombre dorado,'' the gilded one: a Muisca ruler covered in gold dust, rowed onto Lake Guatavita to make offerings to the water. Retellings turned the man into a city, and the city into an empire, and thousands died in the Spanish search for a place that was always a ceremony. The gold offerings were real -- divers really did recover them from the lake. The city never existed. Swipe for the actual gold raft that started it all. →', 'Muisca raft gold Museo del Oro Bogota'),
  (9, 4, '16:30', 'instagram', 'Single image', 'Trivia', 'Amsterdam genuinely has more bicycles than people. And the entire historic centre -- canals, houses, all of it -- is built on more than 11,000 wooden piles driven into the ground. So technically the whole city is floating on a very old, very patient forest. 🚲🌊 #glotemp #Amsterdam', 'Amsterdam canal houses bicycles'),
  (10, 4, '16:30', 'instagram', 'Single image', 'Lost city', 'Pompeii wasn''t destroyed. It was paused. 🌋 Buried under metres of ash in 79 CE, what survived wasn''t just buildings -- it was loaves still in ovens, election slogans on walls, graffiti about who loved whom. The famous body-shaped casts aren''t bodies -- they''re VOIDS left in the hardened ash where bodies had been. Someone worked out you could pour plaster into the gap in the 1860s. History doesn''t get much more literal than that. #glotemp #LostCities', 'Pompeii ruins Vesuvius'),
  (11, 4, '16:30', 'instagram', 'Single image', 'Trivia', 'Vienna keeps winning ''most liveable city'' polls so often it''s basically a part-time job at this point. The State Opera stages a DIFFERENT production almost every single night of the season -- no reruns, no filler, just relentless Austrian excellence. 🎭 #glotemp #Vienna', 'Vienna State Opera building'),
  (12, 4, '16:30', 'instagram', 'Single image', 'Legend', 'Shangri-La isn''t an ancient legend. It''s younger than sliced bread. 🍞 James Hilton invented it in 1933 for his novel ''Lost Horizon'' -- a hidden valley where people barely age. He borrowed loosely from Shambhala, a real Tibetan Buddhist concept, and travel writing he read at the British Museum. He never actually went. In 2001, a real Chinese county officially renamed itself Shangri-La for tourism -- so now a real town carries the name of a place a novelist made up 68 years earlier. Fiction: undefeated. 📖 #glotemp #LostCities', 'Shangri-La county Yunnan mountains China'),
  (13, 4, '16:30', 'instagram', 'Single image', 'Trivia', 'Tango was born in the working-class neighbourhoods of Buenos Aires in the late 1800s -- and the city still has more bookshops per capita than almost anywhere else on Earth. Dance first, read later. Or the other way round. Either way, a lot of feeling per square metre. 💃📚 #glotemp #BuenosAires', 'Buenos Aires street tango'),
  (14, 4, '16:30', 'instagram', 'Single image', 'Lost city', 'Angkor was never actually lost. That''s the plot twist. 🛕 At its peak, this was one of the largest pre-industrial urban complexes anywhere -- a thousand square kilometres of temples, roads and reservoirs. Buddhist monks maintained it continuously the whole time; European visitors described it as early as the 1500s. What happened in 1860 is that Europe finally believed a Frenchman''s travel account and decided it had ''discovered'' a place that had never once stopped being cared for. #glotemp #LostCities', 'Angkor Wat Cambodia temple'),
  (15, 4, '16:30', 'instagram', 'Single image', 'Trivia', 'Athens has been continuously inhabited for over 3,000 years. And the Parthenon -- famous for its perfectly straight lines -- has almost NO straight lines. Its columns subtly curve so that from a distance, they look perfectly straight. Ancient Greek architects: solving optical illusions before optics was a science. 🏛️ #glotemp #Athens', 'Parthenon Athens Acropolis'),
  (16, 4, '16:30', 'instagram', 'Single image', 'Legend', 'Somewhere in the Bay of Douarnenez, Brittany, there''s supposed to be a drowned city with church bells that still ring under the water in bad weather. 🔔🌊 The legend: Ys sat below sea level behind a single gated dyke, the only key hung around the king''s neck -- until his daughter opened it one night, and the sea took everything. There''s a Breton saying: ''When Paris is drowned, Ys will rise again.'' No trace of Ys has ever actually been found in that bay. Doesn''t stop it being a genuinely great bedtime story. #glotemp #LostCities', 'Bay of Douarnenez Brittany coast'),
  (17, 4, '16:30', 'instagram', 'Single image', 'Trivia', 'Chicago once reversed the flow of an entire river. On purpose. In 1900. Still studied today as one of the great engineering flexes in American history. The deep-dish pizza situation and the skyline share exactly one trait: total, unwavering confidence. 🍕🏙️ #glotemp #Chicago', 'Chicago river skyline'),
  (18, 4, '16:30', 'instagram', 'Single image', 'Lost city', 'Troy wasn''t one city. It was at least NINE, stacked on top of each other across 3,000 years. 🏺 When Heinrich Schliemann went digging in 1870, he was in such a hurry to find Homer''s Troy that he drove a trench straight down THROUGH the layer he was actually looking for. The gold he proudly called ''the Treasure of Priam''? It belongs to a layer roughly a thousand years older than any war Homer could have described. #glotemp #LostCities', 'Troy Hisarlik archaeological site Turkey'),
  (19, 4, '16:30', 'instagram', 'Single image', 'Trivia', 'Mumbai''s dabbawalas deliver over 200,000 lunchboxes a day, city-wide, with near-perfect accuracy -- no barcodes, no app, no GPS. Also, the whole city used to be seven separate islands, quietly stitched together over centuries. Mumbai: turning logistics and geography into a personality trait. 🍱🏝️ #glotemp #Mumbai', 'Mumbai dabbawalas lunchbox delivery'),
  (20, 4, '16:30', 'instagram', 'Single image', 'Legend', 'Off the tip of Cornwall, legend says there''s an entire drowned country -- lost in a single night, its church bells still ringing in bad weather. Tristan, of Arthurian legend, is said to be from there. Here''s the real bit underneath the story: rising seas after the last Ice Age genuinely DID drown land around the Isles of Scilly, splitting islands that used to be joined. It just happened over thousands of years, long before the legend''s timeline. Even the myth has a footnote in fact. 🌊⚓ #glotemp #LostCities', 'Land''s End Cornwall Isles of Scilly coast'),
  (21, 4, '16:30', 'instagram', 'Single image', 'Trivia', 'Dublin''s Ha''penny Bridge gets its name from the toll once charged to cross it -- half a penny, cash only, no exceptions. Somehow the nickname outlived the toll by about 150 years. Some branding just sticks. 🌉 #glotemp #Dublin', 'Ha''penny Bridge Dublin'),
  (22, 4, '16:30', 'instagram', 'Single image', 'Lost city', 'We don''t actually know what the people who built Teotihuacan called themselves, or what language they spoke. 🌄 ''Teotihuacan'' is a name the Aztecs gave it CENTURIES after it fell -- they found it already ruined and treated it as sacred ground, as far removed from its builders in time as we are from the Norman Conquest. In 2003, archaeologists opened a tunnel sealed for around 1,800 years and found a floor scattered with pyrite, to imitate stars. #glotemp #LostCities', 'Teotihuacan Avenue of the Dead Mexico'),
  (23, 4, '16:30', 'instagram', 'Single image', 'Trivia', 'Nairobi is one of the only capital cities on Earth with an actual national park inside its limits -- lions, giraffes, the whole cast, a short drive from the skyline. Most cities have a zoo. Nairobi just left the wildlife where it was and built around it. 🦁🏙️ #glotemp #Nairobi', 'Nairobi National Park lions skyline'),
  (24, 4, '16:30', 'instagram', 'Single image', 'Legend', 'Hyperborea was supposed to be a land ''beyond the north wind'' where nobody got sick, nobody grew old, and the sun never really set. Ancient Greek writers described it with total confidence -- while admitting they''d only ever heard about it secondhand, from people who''d also only heard about it. 🧊 Even Herodotus, writing in the 5th century BCE, basically said ''look, I''m just repeating what I was told.'' Cartographers were STILL drawing it on ''serious'' maps 2,000 years later. No evidence. Incredible commitment. #glotemp #LostCities', null),
  (25, 4, '16:30', 'instagram', 'Single image', 'Trivia', 'Madrid is Europe''s highest-altitude capital city, and the Prado holds one of the finest art collections anywhere on the continent. High up, high culture. Coincidence? Probably. Still fun to say. 🎨⛰️ #glotemp #Madrid', 'Prado Museum Madrid'),
  (26, 4, '16:30', 'instagram', 'Single image', 'Lost city', 'For decades, colonial writers insisted Africans couldn''t have built Great Zimbabwe -- and credited it to literally anyone else, including a Biblical queen. 🏯 The truth: it was built by ancestral Shona people, granite walls up to 11 metres high, laid without a drop of mortar. A 1929 excavation PROVED African origin, and the finding was suppressed for decades anyway. Modern Zimbabwe took its name from this site at independence in 1980. #glotemp #LostCities', 'Great Zimbabwe ruins granite walls'),
  (27, 4, '16:30', 'instagram', 'Single image', 'Trivia', 'Jakarta is sinking faster than almost any city on Earth -- part of why Indonesia is literally building a new capital elsewhere. It''s also affectionately nicknamed ''the Big Durian,'' a cheeky nod to New York''s ''Big Apple.'' Same energy, considerably more pungent fruit. 🌆 #glotemp #Jakarta', 'Jakarta skyline Indonesia'),
  (28, 4, '16:30', 'instagram', 'Single image', 'Legend', 'The Seven Cities of Cíbola were supposed to be golden. What Coronado''s expedition actually found in 1540 was a Zuni pueblo called Hawikuh -- real people, real homes, zero gold. 😬 A friar had reported seeing ''a great city'' from a distance the year before. He hadn''t gone closer. He should have gone closer. The golden cities never existed. The people who paid for that mistake were very real. #glotemp #LostCities', 'Hawikuh Zuni pueblo ruins New Mexico'),
  (29, 4, '16:30', 'instagram', 'Single image', 'Trivia', 'Edinburgh''s Old Town and New Town are BOTH UNESCO World Heritage Sites, sitting right next to each other -- a genuinely rare flex. Also: parts of Harry Potter were reportedly written in the city''s cafés. Mild history AND main character energy, on the same street. ✨☕ #glotemp #Edinburgh', 'Edinburgh Old Town skyline'),
  (30, 4, '16:30', 'instagram', 'Single image', 'Legend', 'As an army approached Lake Svetloyar in 1238, legend says the people of Kitezh didn''t fight and didn''t flee. They prayed -- and the whole city sank beneath the lake rather than be taken. 🔔 The story says it''s still down there, and that the pure of heart can still hear its bells ringing under the water. Lake Svetloyar is real -- pilgrims still walk around it today. The city under it was never found, because there''s nothing to find. Real ruins, pure legend, always clearly labelled either way. 🌍 #glotemp #LostCities', 'Lake Svetloyar Russia')
on conflict (day_number, slot_number) do nothing;
