-- The attention layer needs a human-readable name/country per city (for
-- board display) and a place to cache each city's resolved Wikipedia
-- article title (wiki-attention writes this once per city, then reuses
-- it -- never re-derives it on every run).
alter table city_points add column if not exists name text;
alter table city_points add column if not exists country text;
alter table city_points add column if not exists wikipedia_title text;

-- Backfill name/country for all 300 existing rows from the same city
-- list the rest of the site already renders from (cities-data.js).
create temporary table _city_names (city_slug text, name text, country text) on commit drop;

insert into _city_names (city_slug, name, country) values
  ('tokyo', 'Tokyo', 'Japan'),
  ('delhi', 'Delhi', 'India'),
  ('shanghai', 'Shanghai', 'China'),
  ('sao-paulo', 'São Paulo', 'Brazil'),
  ('mexico-city', 'Mexico City', 'Mexico'),
  ('cairo', 'Cairo', 'Egypt'),
  ('mumbai', 'Mumbai', 'India'),
  ('beijing', 'Beijing', 'China'),
  ('osaka', 'Osaka', 'Japan'),
  ('nyc', 'New York', 'USA'),
  ('london', 'London', 'UK'),
  ('paris', 'Paris', 'France'),
  ('toronto', 'Toronto', 'Canada'),
  ('sydney', 'Sydney', 'Australia'),
  ('berlin', 'Berlin', 'Germany'),
  ('dubai', 'Dubai', 'UAE'),
  ('singapore', 'Singapore', 'Singapore'),
  ('hong-kong', 'Hong Kong', 'Hong Kong'),
  ('bangkok', 'Bangkok', 'Thailand'),
  ('istanbul', 'Istanbul', 'Turkey'),
  ('medellin', 'Medellín', 'Colombia'),
  ('bogota', 'Bogotá', 'Colombia'),
  ('buenos-aires', 'Buenos Aires', 'Argentina'),
  ('santiago', 'Santiago', 'Chile'),
  ('lima', 'Lima', 'Peru'),
  ('moscow', 'Moscow', 'Russia'),
  ('seoul', 'Seoul', 'South Korea'),
  ('ankara', 'Ankara', 'Turkey'),
  ('nairobi', 'Nairobi', 'Kenya'),
  ('lagos', 'Lagos', 'Nigeria'),
  ('los-angeles', 'Los Angeles', 'USA'),
  ('chicago', 'Chicago', 'USA'),
  ('miami', 'Miami', 'USA'),
  ('houston', 'Houston', 'USA'),
  ('vancouver', 'Vancouver', 'Canada'),
  ('montreal', 'Montreal', 'Canada'),
  ('san-francisco', 'San Francisco', 'USA'),
  ('guadalajara', 'Guadalajara', 'Mexico'),
  ('atlanta', 'Atlanta', 'USA'),
  ('seattle', 'Seattle', 'USA'),
  ('washington-dc', 'Washington DC', 'USA'),
  ('phoenix', 'Phoenix', 'USA'),
  ('boston', 'Boston', 'USA'),
  ('monterrey', 'Monterrey', 'Mexico'),
  ('dallas', 'Dallas', 'USA'),
  ('minneapolis', 'Minneapolis', 'USA'),
  ('denver', 'Denver', 'USA'),
  ('philadelphia', 'Philadelphia', 'USA'),
  ('san-diego', 'San Diego', 'USA'),
  ('havana', 'Havana', 'Cuba'),
  ('madrid', 'Madrid', 'Spain'),
  ('barcelona', 'Barcelona', 'Spain'),
  ('rome', 'Rome', 'Italy'),
  ('milan', 'Milan', 'Italy'),
  ('amsterdam', 'Amsterdam', 'Netherlands'),
  ('warsaw', 'Warsaw', 'Poland'),
  ('stockholm', 'Stockholm', 'Sweden'),
  ('vienna', 'Vienna', 'Austria'),
  ('prague', 'Prague', 'Czechia'),
  ('budapest', 'Budapest', 'Hungary'),
  ('zurich', 'Zurich', 'Switzerland'),
  ('munich', 'Munich', 'Germany'),
  ('lisbon', 'Lisbon', 'Portugal'),
  ('brussels', 'Brussels', 'Belgium'),
  ('oslo', 'Oslo', 'Norway'),
  ('copenhagen', 'Copenhagen', 'Denmark'),
  ('helsinki', 'Helsinki', 'Finland'),
  ('athens', 'Athens', 'Greece'),
  ('bucharest', 'Bucharest', 'Romania'),
  ('kyiv', 'Kyiv', 'Ukraine'),
  ('dublin', 'Dublin', 'Ireland'),
  ('lyon', 'Lyon', 'France'),
  ('rotterdam', 'Rotterdam', 'Netherlands'),
  ('krakow', 'Kraków', 'Poland'),
  ('hamburg', 'Hamburg', 'Germany'),
  ('edinburgh', 'Edinburgh', 'UK'),
  ('seville', 'Seville', 'Spain'),
  ('porto', 'Porto', 'Portugal'),
  ('sofia', 'Sofia', 'Bulgaria'),
  ('vilnius', 'Vilnius', 'Lithuania'),
  ('bangalore', 'Bangalore', 'India'),
  ('hyderabad', 'Hyderabad', 'India'),
  ('dhaka', 'Dhaka', 'Bangladesh'),
  ('karachi', 'Karachi', 'Pakistan'),
  ('kolkata', 'Kolkata', 'India'),
  ('guangzhou', 'Guangzhou', 'China'),
  ('shenzhen', 'Shenzhen', 'China'),
  ('chengdu', 'Chengdu', 'China'),
  ('wuhan', 'Wuhan', 'China'),
  ('taipei', 'Taipei', 'Taiwan'),
  ('kuala-lumpur', 'Kuala Lumpur', 'Malaysia'),
  ('jakarta', 'Jakarta', 'Indonesia'),
  ('manila', 'Manila', 'Philippines'),
  ('ho-chi-minh', 'Ho Chi Minh City', 'Vietnam'),
  ('hanoi', 'Hanoi', 'Vietnam'),
  ('melbourne', 'Melbourne', 'Australia'),
  ('auckland', 'Auckland', 'New Zealand'),
  ('lahore', 'Lahore', 'Pakistan'),
  ('colombo', 'Colombo', 'Sri Lanka'),
  ('yangon', 'Yangon', 'Myanmar'),
  ('kathmandu', 'Kathmandu', 'Nepal'),
  ('chennai', 'Chennai', 'India'),
  ('pune', 'Pune', 'India'),
  ('tianjin', 'Tianjin', 'China'),
  ('chongqing', 'Chongqing', 'China'),
  ('nanjing', 'Nanjing', 'China'),
  ('perth', 'Perth', 'Australia'),
  ('brisbane', 'Brisbane', 'Australia'),
  ('phnom-penh', 'Phnom Penh', 'Cambodia'),
  ('busan', 'Busan', 'South Korea'),
  ('nagoya', 'Nagoya', 'Japan'),
  ('fukuoka', 'Fukuoka', 'Japan'),
  ('surabaya', 'Surabaya', 'Indonesia'),
  ('xi-an', 'Xi’an', 'China'),
  ('harbin', 'Harbin', 'China'),
  ('adelaide', 'Adelaide', 'Australia'),
  ('ulaanbaatar', 'Ulaanbaatar', 'Mongolia'),
  ('sapporo', 'Sapporo', 'Japan'),
  ('vientiane', 'Vientiane', 'Laos'),
  ('tehran', 'Tehran', 'Iran'),
  ('caracas', 'Caracas', 'Venezuela'),
  ('guayaquil', 'Guayaquil', 'Ecuador'),
  ('quito', 'Quito', 'Ecuador'),
  ('fortaleza', 'Fortaleza', 'Brazil'),
  ('belo-horizonte', 'Belo Horizonte', 'Brazil'),
  ('porto-alegre', 'Porto Alegre', 'Brazil'),
  ('recife', 'Recife', 'Brazil'),
  ('cali', 'Cali', 'Colombia'),
  ('montevideo', 'Montevideo', 'Uruguay'),
  ('curitiba', 'Curitiba', 'Brazil'),
  ('johannesburg', 'Johannesburg', 'South Africa'),
  ('cape-town', 'Cape Town', 'South Africa'),
  ('kinshasa', 'Kinshasa', 'DRC'),
  ('addis-ababa', 'Addis Ababa', 'Ethiopia'),
  ('accra', 'Accra', 'Ghana'),
  ('dar-es-salaam', 'Dar es Salaam', 'Tanzania'),
  ('casablanca', 'Casablanca', 'Morocco'),
  ('dakar', 'Dakar', 'Senegal'),
  ('algiers', 'Algiers', 'Algeria'),
  ('tunis', 'Tunis', 'Tunisia'),
  ('riyadh', 'Riyadh', 'Saudi Arabia'),
  ('doha', 'Doha', 'Qatar'),
  ('abu-dhabi', 'Abu Dhabi', 'UAE'),
  ('amman', 'Amman', 'Jordan'),
  ('tel-aviv', 'Tel Aviv', 'Israel'),
  ('beirut', 'Beirut', 'Lebanon'),
  ('muscat', 'Muscat', 'Oman'),
  ('kuwait-city', 'Kuwait City', 'Kuwait'),
  ('jeddah', 'Jeddah', 'Saudi Arabia'),
  ('baghdad', 'Baghdad', 'Iraq'),
  ('milton-keynes', 'Milton Keynes', 'UK'),
  ('kyoto', 'Kyoto', 'Japan'),
  ('hiroshima', 'Hiroshima', 'Japan'),
  ('nara', 'Nara', 'Japan'),
  ('kanazawa', 'Kanazawa', 'Japan'),
  ('yokohama', 'Yokohama', 'Japan'),
  ('kobe', 'Kobe', 'Japan'),
  ('sendai', 'Sendai', 'Japan'),
  ('nagasaki', 'Nagasaki', 'Japan'),
  ('naha', 'Naha', 'Japan'),
  ('takayama', 'Takayama', 'Japan'),
  ('beppu', 'Beppu', 'Japan'),
  ('lanzarote', 'Lanzarote', 'Spain'),
  ('gran-canaria', 'Gran Canaria', 'Spain'),
  ('salzburg', 'Salzburg', 'Austria'),
  ('hallstatt', 'Hallstatt', 'Austria'),
  ('bruges', 'Bruges', 'Belgium'),
  ('interlaken', 'Interlaken', 'Switzerland'),
  ('chania', 'Chania', 'Greece'),
  ('dubrovnik', 'Dubrovnik', 'Croatia'),
  ('split', 'Split', 'Croatia'),
  ('ljubljana', 'Ljubljana', 'Slovenia'),
  ('bled', 'Bled', 'Slovenia'),
  ('faro', 'Faro', 'Portugal'),
  ('valletta', 'Valletta', 'Malta'),
  ('reykjavik', 'Reykjavík', 'Iceland'),
  ('tromso', 'Tromsø', 'Norway'),
  ('gdansk', 'Gdańsk', 'Poland'),
  ('matera', 'Matera', 'Italy'),
  ('funchal', 'Funchal', 'Portugal'),
  ('ronda', 'Ronda', 'Spain'),
  ('colmar', 'Colmar', 'France'),
  ('tbilisi', 'Tbilisi', 'Georgia'),
  ('batumi', 'Batumi', 'Georgia'),
  ('almaty', 'Almaty', 'Kazakhstan'),
  ('astana', 'Astana', 'Kazakhstan'),
  ('tashkent', 'Tashkent', 'Uzbekistan'),
  ('bishkek', 'Bishkek', 'Kyrgyzstan'),
  ('wadi-musa', 'Wadi Musa (Petra)', 'Jordan'),
  ('luxor', 'Luxor', 'Egypt'),
  ('aswan', 'Aswan', 'Egypt'),
  ('sharm-el-sheikh', 'Sharm El Sheikh', 'Egypt'),
  ('paphos', 'Paphos', 'Cyprus'),
  ('salalah', 'Salalah', 'Oman'),
  ('aqaba', 'Aqaba', 'Jordan'),
  ('marrakech', 'Marrakech', 'Morocco'),
  ('chefchaouen', 'Chefchaouen', 'Morocco'),
  ('essaouira', 'Essaouira', 'Morocco'),
  ('zanzibar-city', 'Zanzibar City', 'Tanzania'),
  ('kigali', 'Kigali', 'Rwanda'),
  ('victoria-falls', 'Victoria Falls', 'Zimbabwe'),
  ('lalibela', 'Lalibela', 'Ethiopia'),
  ('cusco', 'Cusco', 'Peru'),
  ('antigua-guatemala', 'Antigua Guatemala', 'Guatemala'),
  ('ushuaia', 'Ushuaia', 'Argentina'),
  ('bariloche', 'San Carlos de Bariloche', 'Argentina'),
  ('salvador', 'Salvador', 'Brazil'),
  ('iguazu', 'Puerto Iguazú', 'Argentina'),
  ('san-miguel-de-allende', 'San Miguel de Allende', 'Mexico'),
  ('oaxaca', 'Oaxaca', 'Mexico'),
  ('banos', 'Baños', 'Ecuador'),
  ('punta-del-este', 'Punta del Este', 'Uruguay'),
  ('cartagena', 'Cartagena', 'Colombia'),
  ('nassau', 'Nassau', 'Bahamas'),
  ('bridgetown', 'Bridgetown', 'Barbados'),
  ('george-town-cayman', 'George Town', 'Cayman Islands'),
  ('tulum', 'Tulum', 'Mexico'),
  ('cancun', 'Cancún', 'Mexico'),
  ('luang-prabang', 'Luang Prabang', 'Laos'),
  ('hoi-an', 'Hoi An', 'Vietnam'),
  ('hue', 'Hue', 'Vietnam'),
  ('da-nang', 'Da Nang', 'Vietnam'),
  ('da-lat', 'Da Lat', 'Vietnam'),
  ('siem-reap', 'Siem Reap', 'Cambodia'),
  ('bali-denpasar', 'Bali (Denpasar)', 'Indonesia'),
  ('ubud', 'Ubud', 'Indonesia'),
  ('chiang-mai', 'Chiang Mai', 'Thailand'),
  ('chiang-rai', 'Chiang Rai', 'Thailand'),
  ('krabi', 'Krabi', 'Thailand'),
  ('phuket', 'Phuket', 'Thailand'),
  ('boracay', 'Boracay', 'Philippines'),
  ('el-nido', 'El Nido', 'Philippines'),
  ('george-town-penang', 'George Town', 'Malaysia'),
  ('vang-vieng', 'Vang Vieng', 'Laos'),
  ('koh-samui', 'Koh Samui', 'Thailand'),
  ('jaipur', 'Jaipur', 'India'),
  ('goa', 'Goa (Panaji)', 'India'),
  ('varanasi', 'Varanasi', 'India'),
  ('udaipur', 'Udaipur', 'India'),
  ('jaisalmer', 'Jaisalmer', 'India'),
  ('munnar', 'Munnar', 'India'),
  ('galle', 'Galle', 'Sri Lanka'),
  ('pokhara', 'Pokhara', 'Nepal'),
  ('male', 'Malé', 'Maldives'),
  ('yangshuo', 'Yangshuo', 'China'),
  ('queenstown', 'Queenstown', 'New Zealand'),
  ('nadi', 'Nadi', 'Fiji'),
  ('bora-bora', 'Bora Bora', 'French Polynesia'),
  ('granada-nicaragua', 'Granada', 'Nicaragua'),
  ('san-pedro-la-laguna', 'San Pedro La Laguna', 'Guatemala'),
  ('las-vegas', 'Las Vegas', 'USA'),
  ('venice', 'Venice', 'Italy'),
  ('florence', 'Florence', 'Italy'),
  ('ibiza', 'Ibiza', 'Spain'),
  ('santorini', 'Santorini', 'Greece'),
  ('new-orleans', 'New Orleans', 'USA'),
  ('key-west', 'Key West', 'USA'),
  ('whistler', 'Whistler', 'Canada'),
  ('banff', 'Banff', 'Canada'),
  ('mykonos', 'Mykonos', 'Greece'),
  ('capri', 'Capri', 'Italy'),
  ('amalfi', 'Amalfi', 'Italy'),
  ('positano', 'Positano', 'Italy'),
  ('lake-como', 'Como', 'Italy'),
  ('st-tropez', 'Saint-Tropez', 'France'),
  ('bordeaux', 'Bordeaux', 'France'),
  ('monaco', 'Monaco', 'Monaco'),
  ('zermatt', 'Zermatt', 'Switzerland'),
  ('innsbruck', 'Innsbruck', 'Austria'),
  ('san-sebastian', 'San Sebastián', 'Spain'),
  ('cordoba', 'Córdoba', 'Spain'),
  ('rhodes', 'Rhodes', 'Greece'),
  ('heraklion', 'Heraklion', 'Greece'),
  ('jerusalem', 'Jerusalem', 'Israel'),
  ('tangier', 'Tangier', 'Morocco'),
  ('sousse', 'Sousse', 'Tunisia'),
  ('hurghada', 'Hurghada', 'Egypt'),
  ('mombasa', 'Mombasa', 'Kenya'),
  ('st-lucia', 'Castries', 'Saint Lucia'),
  ('aruba', 'Oranjestad', 'Aruba'),
  ('curacao', 'Willemstad', 'Curaçao'),
  ('puerto-vallarta', 'Puerto Vallarta', 'Mexico'),
  ('playa-del-carmen', 'Playa del Carmen', 'Mexico'),
  ('aguas-calientes', 'Aguas Calientes', 'Peru'),
  ('valparaiso', 'Valparaíso', 'Chile'),
  ('mendoza', 'Mendoza', 'Argentina'),
  ('langkawi', 'Langkawi', 'Malaysia'),
  ('ha-long', 'Ha Long', 'Vietnam'),
  ('sapa', 'Sapa', 'Vietnam'),
  ('pai', 'Pai', 'Thailand'),
  ('bagan', 'Bagan', 'Myanmar'),
  ('kandy', 'Kandy', 'Sri Lanka'),
  ('shimla', 'Shimla', 'India'),
  ('rishikesh', 'Rishikesh', 'India'),
  ('amritsar', 'Amritsar', 'India'),
  ('gyeongju', 'Gyeongju', 'South Korea'),
  ('jeju', 'Jeju City', 'South Korea'),
  ('kota-kinabalu', 'Kota Kinabalu', 'Malaysia'),
  ('cairns', 'Cairns', 'Australia'),
  ('gold-coast', 'Gold Coast', 'Australia');

update city_points cp
set name = cn.name,
    country = cn.country
from _city_names cn
where cn.city_slug = cp.city_slug;
